In [91]:
from google.colab import files
uploaded = files.upload()

Saving Dataset for Data Analytics - Sheet1.csv to Dataset for Data Analytics - Sheet1.csv

In [92]:
import pandas as pd

In [93]:
df = pd.read_csv('Dataset for Data Analytics - Sheet1.csv')
print("Shape:", df.shape)

Shape: (1200, 14)

In [94]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [95]:
print("Data types:")
print(df.dtypes)

Data types:
OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

In [96]:
print("\nMissing values:")
print(df.isnull().sum())

Missing values:
OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [97]:
print("\nDuplicate OrderIDs:", df['OrderID'].duplicated().sum())

Duplicate OrderIDs: 0

In [98]:
print("Full row duplicates:", df.duplicated().sum())

Full row duplicates: 0

In [99]:
change_log = []

In [100]:
n_before = df['CouponCode'].isnull().sum()

df['CouponCode'] = df['CouponCode'].fillna('NONE')

change_log.append(('CR001', 'Filled missing CouponCode with NONE (no coupon used)', f'{n_before} rows fixed', 'Resolved'))
print(f"Fixed {n_before} rows")

Fixed 309 rows

In [101]:
print(df.isnull().sum())

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [102]:
n_id_dupes = df.duplicated(subset='OrderID').sum()
df = df.drop_duplicates(subset='OrderID', keep='first')

n_full_dupes = df.duplicated().sum()
df = df.drop_duplicates()

change_log.append(('CR002', 'Checked and removed duplicate OrderIDs', f'{n_id_dupes} rows removed', 'Resolved'))
change_log.append(('CR003', 'Checked and removed full-row duplicates', f'{n_full_dupes} rows removed', 'Resolved'))
print(f"Removed {n_id_dupes} ID duplicates, {n_full_dupes} full duplicates")

Removed 0 ID duplicates, 0 full duplicates

In [103]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce').dt.strftime('%Y-%m-%d')

bad_dates = df['Date'].isnull().sum()
change_log.append(('CR004', 'Verified/standardized Date to ISO 8601 (YYYY-MM-DD)', f'{bad_dates} invalid dates found', 'Resolved'))
print(f"Invalid dates: {bad_dates}")

Invalid dates: 0

In [104]:
text_cols = ['OrderID', 'CustomerID', 'Product', 'ShippingAddress',
             'PaymentMethod', 'OrderStatus', 'TrackingNumber',
             'CouponCode', 'ReferralSource']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

change_log.append(('CR005', 'Trimmed whitespace on all text columns', 'All rows', 'Resolved'))

In [105]:
for col in ['UnitPrice', 'TotalPrice']:
    df[col] = df[col].round(2)

change_log.append(('CR006', 'Rounded UnitPrice and TotalPrice to 2 decimals', 'All rows', 'Resolved'))

In [106]:
calc = (df['Quantity'] * df['UnitPrice']).round(2)
mismatch = (calc - df['TotalPrice']).abs() > 0.01
n_mismatch = mismatch.sum()

df.loc[mismatch, 'TotalPrice'] = calc[mismatch]

change_log.append(('CR007', 'Verified/corrected TotalPrice = Quantity x UnitPrice', f'{n_mismatch} rows corrected', 'Resolved'))
print(f"Corrected {n_mismatch} mismatches")

Corrected 0 mismatches

In [107]:
assert df['OrderID'].duplicated().sum() == 0, "FAIL: duplicate OrderIDs remain"
assert df['Date'].isnull().sum() == 0, "FAIL: bad dates remain"
assert df.isnull().sum().sum() == 0, "FAIL: missing values remain"

print("✅ VERIFICATION PASSED")

✅ VERIFICATION PASSED

In [108]:
print(df.isnull().sum())
print("\nFinal shape:", df.shape)
df.head()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

Final shape: (1200, 14)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [109]:
df.to_csv('Cleaned_Dataset for Data Analytics - Sheet1.csv', index=False)

change_log_df = pd.DataFrame(change_log, columns=['Change ID', 'Description', 'Impact', 'Status'])
change_log_df.to_csv('change_log.csv', index=False)

print(change_log_df.to_string(index=False))

Change ID                                          Description                Impact   Status
    CR001 Filled missing CouponCode with NONE (no coupon used)        309 rows fixed Resolved
    CR002               Checked and removed duplicate OrderIDs        0 rows removed Resolved
    CR003              Checked and removed full-row duplicates        0 rows removed Resolved
    CR004  Verified/standardized Date to ISO 8601 (YYYY-MM-DD) 0 invalid dates found Resolved
    CR005               Trimmed whitespace on all text columns              All rows Resolved
    CR006       Rounded UnitPrice and TotalPrice to 2 decimals              All rows Resolved
    CR007 Verified/corrected TotalPrice = Quantity x UnitPrice      0 rows corrected Resolved

In [110]:
files.download('Cleaned_Dataset for Data Analytics - Sheet1.csv')
files.download('change_log.csv')